### ISSUE TITLE
position 

### ISSUE THREAD

**Issue by KoosOverbeeke** [carcam/plg_readingtime#16]
Hi Carlos, you invited me to contact you 

as you can see here https://www.slagkracht-outsourcing.nl/de-outsourcing-belofte

the readingtime message is placed at the top of any article.

I would like it placed below the opening picture on the left side. 

The other text you see above right going to be also somewhere els but that it not of your concern.

Would my wish be possible without using a standard module position? (maybe with some php code placed in the article {source} ....{/source} ??
Thanks

**Comment by carcam** [comment]
Hi @KoosOverbeeke ,
Thank you very much for reaching me out!! Yes I requested you contact me as I wanted to have the opportunity to understand your issues with the plugin so that I can make it a bit better for you and other users ;). In any case as Joomla user, thank you very much for taking the time to review it ;)

Regarding your request, the inmmediate answer to your request is that you create a template overrides for your article page. This way you can use the plugin override capabilities and insert it whenever you want.

A quick guide to do this will be:

1. Edit plugin settings and set it to "hide plugin output"
2. Create a template override for your article view and place this code just below the picture:

`<div class="estimated-reading-time"><?php echo $this->item->readingtime;?> </div>`

That will place the text exactly where you need it ;)

For further reference please check the plugin documentation: https://extensions.hepta.es/support/documentation/estimated-reading-time/estimated-reading-time

This is template dependant and you can check how it shows in one of my sites with no template overrides ;)

https://manualesjoomla.es/blog/196-mastermind-joomla-un-podcast-para-potenciar-tus-proyectos-web
